cc_library(
  name = "stdlib",
  deps = [
    ":abort",
    ":arithmetic",
  ],
  visibility = ["//visibility:public"],
)

cc_library(
    name = "abort",
    srcs = [
        "abort.cc",
    ],
    hdrs = [
        "abort.h",
    ],
)

cc_library(
    name = "arithmetic",
    srcs = [
        "arithmetic.cc",
    ],
    hdrs = [
        "arithmetic.h",
    ]
)
