#!/bin/sh

BINARY=$(basename $0);

if [ -z "$TOOLCHAIN_REPOSITORY" ]; then
  TOOLCHAIN_REPOSITORY="toolchain-i686-elf";
fi;

if [ -z "$TARGET_TRIPLET" ]; then
  TARGET_TRIPLET="i686-elf"
fi;

set -euo pipefail
exec "external/${TOOLCHAIN_REPOSITORY}/toolchain/bin/${TARGET_TRIPLET}-${BINARY}" "$@"
