language: cpp

env:
  global:
    - BAZEL_VERSION=4.0.0
    - CC=gcc-7
    - CXX=g++-7

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - qemu
      env:
        - BAZEL_OS=linux ARCH_CONFIG=i386
        - BAZEL_OS=linux ARCH_CONFIG=i386-linux-premade
        global:
          - SHA256SUM="sha256sum --check"
    - os: osx
      osx_image: xcode12
      addons:
        homebrew:
          packages:
            - qemu
      env:
        - BAZEL_OS=darwin ARCH_CONFIG=i386
        - BAZEL_OS=darwin ARCH_CONFIG=i386-darwin-premade
        global:
          - SHA256SUM="shasum -a 256 -c"

before_install:
  - tools/scripts/before_install.sh "${BAZEL_VERSION}" "${BAZEL_OS}" "${SHA256SUM}"

script:
  - tools/scripts/continuous.sh "${ARCH_CONFIG}"

notifications:
  email: false
