dist: trusty
language: cpp


cache:
  directories:
    - $HOME/.bazel_repository_cache
    - $HOME/.cache/bazel/output

os:
  - linux
  - osx

env:
  - V=0.29.0

addons:
  apt:
    update: true

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      OS=darwin
      function sha256sum() { shasum -a 256 "$@" ; }
    else
      OS=linux
      LD_LIBRARY_PATH=/usr/local/lib64/:$LD_LIBRARY_PATH
      export LD_LIBRARY_PATH
    fi
    URL="https://github.com/bazelbuild/bazel/releases/download/${V}/bazel-${V}-installer-${OS}-x86_64.sh"
    wget -O install.sh "${URL}"
  - |
    chmod +x install.sh
    ./install.sh --user
    rm -f install.sh


script:
  - |
    bazel \
      --output_base="$HOME/.cache/bazel/output" \
      --batch \
      --host_jvm_args=-Xmx500m \
      --host_jvm_args=-Xms500m \
      test \
      --config ci \
      --experimental_repository_cache="$HOME/.bazel_repository_cache" \
      //kernel/... //libc/...
  - |
    bazel \
      --output_base="$HOME/.cache/bazel/output" \
      --batch \
      --host_jvm_args=-Xmx500m \
      --host_jvm_args=-Xms500m \
      build \
      --config ci \
      --config "i386-${OS}-premade" \
      --experimental_repository_cache="$HOME/.bazel_repository_cache" \
      //kernel
notifications:
  email: false
