# trusty beta image has jdk8, gcc4.8.4
dist: trusty
# Not technically required but suppresses 'Ruby' in Job status message.
language: java

os:
  - linux

env:
  - V=0.13.0

before_install:
  - |
    OS=linux
    URL="https://github.com/bazelbuild/bazel/releases/download/${V}/bazel-${V}-installer-${OS}-x86_64.sh"
    wget -O install.sh "${URL}"
  - sha256sum --check tools/checksums/bazel
  - |
    chmod +x install.sh
    ./install.sh --user
    rm -f install.sh


script:
  - |
    bazel \
      --batch \
      --host_jvm_args=-Xmx500m \
      --host_jvm_args=-Xms500m \
      test \
      --experimental_repository_cache="$HOME/.bazel_repository_cache" \
      //kernel/... //libc/...

notifications:
  email: false
