dist: trusty
language: cpp
osx_image: xcode12

os:
  - linux
  - osx

env:
  - V=4.0.0

addons:
  apt:
    update: true

before_install:
  - |
    case "${TRAVIS_OS_NAME}" in
      osx)
        export OS=darwin
        ;;
      linux)
        export OS=linux
        ;;
      *)
        echo "${TRAVIS_OS_NAME} is not a supported OS."
        exit 1
    esac
  - tools/scripts/before_install.sh

script:
  - tools/scripts/continuous.sh
notifications:
  email: false
