language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - qemu
      env:
        - MATRIX_EVAL="BAZEL_OS=linux && CC=gcc-7 && CXX=g++-7"
    - os: osx
      osx_image: xcode12
      addons:
        homebrew:
          packages:
            - qemu
      env:
        - MATRIX_EVAL="BAZEL_OS=darwin && CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"
  - tools/scripts/before_install.sh

script:
  - tools/scripts/continuous.sh
notifications:
  email: false
