language: cpp

env:
  global:
    - BAZEL_VERSION=4.0.0
    - CC=gcc-7
    - CXX=g++-7

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - BAZEL_OS=linux CONFIG=ci
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - qemu
      env:
        - BAZEL_OS=linux CONFIG=i386
        - BAZEL_OS=linux CONFIG=i386-linux-premade
    - os: osx
      osx_image: xcode12
      env:
        - BAZEL_OS=darwin CONFIG=ci
    - os: osx
      osx_image: xcode12
      addons:
        homebrew:
          packages:
            - qemu
      env:
        - BAZEL_OS=darwin CONFIG=i386
        - BAZEL_OS=darwin CONFIG=i386-darwin-premade

before_install:
  - tools/scripts/before_install.sh "${BAZEL_VERSION}" "${BAZEL_OS}"

script:
  - tools/scripts/continuous.sh "${CONFIG}"

notifications:
  email: false
