language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - qemu
      env:
        - BAZEL_OS="linux"
    - os: osx
      osx_image: xcode12
      addons:
        homebrew:
          packages:
            - qemu
      env:
        - BAZEL_OS="darwin"

env:
  - BAZEL_VERSION="4.0.0"
  - CC="gcc-7"
  - CXX="g++-7"

before_install:
  - tools/scripts/before_install.sh

script:
  - tools/scripts/continuous.sh
notifications:
  email: false
