dist: trusty
language: cpp

os:
  - linux
  - osx

env:
  - V=0.29.0

addons:
  apt:
    update: true

before_install:
  - |
    case "${TRAVIS_OS_NAME}" in
      osx)
        export OS=darwin
        ;;
      linux)
        export OS=linux
        ;;
      *)
        echo "${TRAVIS_OS_NAME} is not a supported OS."
        exit 1
    esac
  - |
    if [[ "${OS}" == "linux" ]]; then
      LD_LIBRARY_PATH=/usr/local/lib64/:$LD_LIBRARY_PATH
      export LD_LIBRARY_PATH
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      sudo apt-get update
      sudo apt-get install -y libstdc++6 gcc-7 g++-7 qemu
    fi
    if [[ "${OS}" == "darwin" ]]; then
      brew install qemu
    fi
  - wget -O install.sh "https://github.com/bazelbuild/bazel/releases/download/${V}/bazel-${V}-installer-${OS}-x86_64.sh"
  - |
    case "${OS}" in
      darwin)
        shasum -a 256 -c "tools/checksums/bazel-${V}-installer-${OS}-x86_64"
        ;;
      linux)
        sha256sum --check "tools/checksums/bazel-${V}-installer-${OS}-x86_64"
        ;;
      *)
        echo "${OS} is not a supported OS."
        exit 1
    esac
  - |
    chmod +x install.sh
    ./install.sh --user
    rm -f install.sh


script:
  - tools/scripts/continuous.sh
notifications:
  email: false
