dist: trusty
language: cpp


cache:
  directories:
    - $HOME/.bazel_repository_cache
    - $HOME/.cache/bazel/output

os:
  - linux
  - osx

env:
  - V=0.29.0

addons:
  apt:
    update: true

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      OS=darwin
      function check_hash() { shasum -a 256 -c "$@" ; }
    else
      OS=linux
      function check_hash() { sha256sum --check "$@" ; }
      LD_LIBRARY_PATH=/usr/local/lib64/:$LD_LIBRARY_PATH
      export LD_LIBRARY_PATH
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      sudo apt-get update
      sudo apt-get install -y libstdc++6 gcc-7 g++-7
    fi
    URL="https://github.com/bazelbuild/bazel/releases/download/${V}/bazel-${V}-installer-${OS}-x86_64.sh"
    wget -O install.sh "${URL}"
  - check_hash tools/checksums/bazel-${V}-installer-${OS}-x86_64
  - |
    chmod +x install.sh
    ./install.sh --user
    rm -f install.sh


script:
  - |
    bazel \
      --output_base="$HOME/.cache/bazel/output" \
      --batch \
      --host_jvm_args=-Xmx500m \
      --host_jvm_args=-Xms500m \
      test \
      --config ci \
      --experimental_repository_cache="$HOME/.bazel_repository_cache" \
      //kernel/... //libc/...
  - |
    bazel \
      --output_base="$HOME/.cache/bazel/output" \
      --batch \
      --host_jvm_args=-Xmx500m \
      --host_jvm_args=-Xms500m \
      build \
      --config ci \
      --config "i386-${OS}-premade" \
      --experimental_repository_cache="$HOME/.bazel_repository_cache" \
      //kernel
notifications:
  email: false
