language: cpp

_env:
  _actions:
    - &action_build
        ACTION=build
    - &action_test
        ACTION=test

  _configs:
    - &config_ci
        CONFIG=ci
    - &config_i386
        CONFIG=i386
    - &config_i386_darwin_premade
        CONFIG=i386-darwin-premade
    - &config_i386_linux_premade
        CONFIG=i386-linux-premade

env:
  global:
    - BAZEL_VERSION=4.0.0
    - CC=gcc-7
    - CXX=g++-7
    - CACHE=true
  jobs:
    - ACTION=test


cache:
  directories:
    - ${HOME}/${TRAVIS_OS_NAME}/.bazel_repository_cache
    - ${HOME}/${TRAVIS_OS_NAME}/.cache/bazel/output

_jobs:
  _linux: &linux
    os: linux
    dist: trusty
    addons:
      apt: &linux_apt
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7

  _osx: &osx
    os: osx
    osx_image: xcode12


jobs:
  include:
    - <<: *linux
      env:
        - *action_test
        - *config_ci
    - <<: *osx
      env:
        - *action_test
        - *config_ci

    - <<: *linux
      addons:
        apt:
          <<: *linux_apt
          packages:
            - g++-7
            - bison
            - build-essential
            - flex
            - libgmp3-dev
            - libmpc-dev
            - libmpfr-dev
            - texinfo
      env:
        - *action_build
        - *config_i386
    - <<: *linux
      addons:
        apt:
          <<: *linux_apt
          packages:
            - g++-7
            - qemu
            - bison
            - build-essential
            - flex
            - libgmp3-dev
            - libmpc-dev
            - libmpfr-dev
            - texinfo
      env:
        - *action_test
        - *config_i386
    - <<: *linux
      addons:
        apt:
          <<: *linux_apt
          packages:
            - g++-7
            - qemu
      env:
        - *action_test
        - *config_i386_linux_premade

    - <<: *osx
      addons:
        homebrew:
          packages:
            - bison
            - flex
            - gmp
            - libmpc
            - mpfr
            - texinfo
      env:
        - *action_build
        - *config_i386
    - <<: *osx
      addons:
        homebrew:
          packages:
            - qemu
            - bison
            - flex
            - libmpc
            - mpfr
            - texinfo
      env:
        - *action_test
        - *config_i386
    - <<: *osx
      addons:
        homebrew:
          packages:
            - qemu
      env:
        - *action_test
        - *config_i386_darwin_premade

before_install:
  - |
    case ${TRAVIS_OS_NAME} in
      osx)
        BAZEL_OS=darwin
        ;;
      linux)
        BAZEL_OS=linux
        ;;
    esac
  - tools/scripts/install_bazel.sh "${BAZEL_VERSION}" "${BAZEL_OS}"

script:
  - tools/scripts/run_bazel.sh "${ACTION}" "${CONFIG}" "${CACHE}"

notifications:
  email: false
