dist: trusty
language: cpp

cache:
  directories:
    - $HOME/.bazel_repository_cache
    - $HOME/.cache/bazel/output

os:
  - linux
  - osx

env:
  - V=0.13.0

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      OS=darwin
      function sha256sum() { shasum -a 256 --portable "$@" ; }
    else
      OS=linux
    fi
    URL="https://github.com/bazelbuild/bazel/releases/download/${V}/bazel-${V}-installer-${OS}-x86_64.sh"
    wget -O install.sh "${URL}"
#  - sha256sum --check tools/checksums/bazel
  - |
    chmod +x install.sh
    ./install.sh --user
    rm -f install.sh


script:
  - |
    bazel \
      --output_base=$HOME/.cache/bazel/output \
      --batch \
      --host_jvm_args=-Xmx500m \
      --host_jvm_args=-Xms500m \
      test \
      --config ci \
      --experimental_repository_cache="$HOME/.bazel_repository_cache" \
      //kernel/... //libc/...

notifications:
  email: false
