package(default_visibility=["//visibility:public"])

load("//kernel/arch:arch.bzl", "arch_library")

arch_library(name = "tty")

arch_library(name = "memory")

arch_library(name = "boot")

arch_library(name = "io_port")
