package(default_visibility=["//visibility:public"])

load("//kernel/arch:arch.bzl", "arch_library")

arch_library(name = "tty")

arch_library(name = "gdt")

arch_library(name = "memory_detection")

arch_library(name = "boot")

