cc_library(
    name = "descriptor",
    srcs = [
        "descriptor.cc",
    ],
    hdrs = [
        "descriptor.h",
    ],
)

cc_test(
    name = "descriptor_test",
    srcs = [
        "descriptor_test.cc",
    ],
    deps = [
        ":descriptor",
        "@com_google_googletest//:gtest",
    ],
)
