package(default_visibility = ["//kernel/arch/i386:__subpackages__"])

cc_library(
    name = "io_port",
    srcs = [
        "io_port.cc",
    ],
    hdrs = [
        "//kernel/arch:io_port.h",
    ],
    visibility = ["//kernel/arch:__pkg__"],
)
