package(default_visibility = ["//visibility:public"])

cc_library(
  name = "tty",
  srcs = [
    "tty.cc"
  ],
  hdrs = [
    "vga.h",
    "//kernel/arch:tty.h",
  ],
  deps = [
    "//libc/string",
  ],
  tags = [
    "manual"
  ]
)
