package(default_visibility=["//visibility:public"])

cc_library(
  name = "tty",
  srcs = [
    "tty.cc"
  ],
  hdrs = [
    "//kernel/arch:tty.h"
  ]
)

cc_library(
  name = "gdt",
  srcs = [
    "gdt.cc"
  ],
  hdrs = [
    "//kernel/arch:gdt.h",
  ]
)
