load("//kernel:templates.bzl", "kernel_library")

package(default_visibility = ["//kernel/arch/i386:__subpackages__"])

kernel_library(
    name = "instructions",
    hdrs = [
        "instructions.h",
    ],
)
