name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-and-test:
    needs: wait-for-docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/ryrose/smouth-os:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Build
        run: zig build
      - name: Test (unit)
        run: zig build test
      - name: Test (kernel)
        run: zig build test-x86
      - name: Test (arch)
        run: zig build test-arch-x86
